server:
  port: 9091

spring:
  kafka:    
    topics: newTopic
    consumer:
      group-id: "group1"

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
